trigger:
  branches:
    include:
    - master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchTags: true
  - task: UseDotNet@2
    displayName: set dotnet version
    inputs:
      version: 8.0.x
  - task: DotNetCoreCLI@2
    displayName: dotnet build -c Release
    inputs:
      command: build
      arguments: -c Release
  - task: DotNetCoreCLI@2
    displayName: dotnet test -c Release --no-build
    inputs:
      command: test
      arguments: -c Release --no-build
  - task: DotNetCoreCLI@2
    displayName: dotnet pack -c Release --no-build
    inputs:
      command: custom
      custom: pack
      arguments: -c Release --no-build
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      searchPatternPush: Entities\bin\Release\*.nupkg
      feedPublish: $(NuGetFeedId)
      allowPackageConflicts: true
