trigger:
  branches:
    include:
    - dev
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchTags: true
  - task: UseDotNet@2
    displayName: set dotnet version
    inputs:
      version: 8.0.x
  - task: DotNetCoreCLI@2
    displayName: dotnet build -c Debug
    inputs:
      command: build
      arguments: -c Debug
  - task: DotNetCoreCLI@2
    displayName: dotnet test -c Debug --no-build
    inputs:
      command: test
      arguments: -c Debug --no-build
  - task: DotNetCoreCLI@2
    displayName: dotnet pack -c Debug --no-build --include-symbols --include-source --version-suffix dbg
    inputs:
      command: pack
      arguments: -c Debug --no-build --include-symbols --include-source --version-suffix dbg
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      searchPatternPush: $(Build.ArtifactStagingDirectory)/*.nupkg
      feedPublish: $(NuGetFeedId)
      allowPackageConflicts: true
