trigger:
  branches:
    include:
    - master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchTags: true
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**/*.csproj'
      arguments: -c Release
  - task: UseDotNet@2
    displayName: set dotnet version
    inputs:
      version: 8.0.x
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      searchPatternPush: Entities\bin\Release\*.nupkg
      feedPublish: bf58cb17-b64e-4d1d-aa47-1090a4336e86/1aa5da4a-a967-430f-9c0a-75a8eb669cab
      allowPackageConflicts: true
...
